language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run-script build
deploy:
  provider: firebase
  token:
    secure: "1/Q5lKK4AhIZxvAx0BUmCjtYw5NR7cSlI3kBCNA9wpGrE" 
  project: "kagoal"
  branches:
    only:
      - release