language: generic # no-frills build
script:
  - npm install
    - npm run build
deploy:
  provider: firebase
  token:
    secure: "1/Q5lKK4AhIZxvAx0BUmCjtYw5NR7cSlI3kBCNA9wpGrE" 
  project: "kagoal"
  branches:
    only:
      - release